baseURL = "https://pa-perz.com"
languageCode = "en-us"
title = "Pablo Pérez"
theme = "cactus"
#copyright =
#disqusShortname = "example"
#googleAnalytics = "UA-1234-5"


#summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Services"
url = "/services"
weight = 2

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 3

[[menu.main]]
name = "Work"
url = "/work"
weight = 4

[[menu.main]]
name = "Setup"
url = "/setup"
weight = 5

[markup]
[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "dracula"
tabWidth = 4

[params]

colortheme = "dark" # dark, light, white, or classic
rss = true # generate rss feed. default value is false
googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
showAllPostsArchive = false # default

# Home page settings
description = """
Hi, I'm Pablo Pérez. I'm a software developer, currently focused in backend microservices written in Java and/or Kotlin.
I work at AYESA, and study my degree at Universitat Oberta de Catalunya.
I live in Tenerife, Canary Islands, Spain.
"""
mainSection = "posts" # your main section
showAllPostsOnHomePage = false # default
postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
tagsOverview = true # show tags overview by default.
showProjectsList = true # show projects list by default (if projects data file exists).
#projectsUrl = "https://github.com/gohugoio" # title link for projects list

# https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
dateFormat = "2006-01-02" # default

# Post page settings
show_updated = true # default
showReadTime = true # default

#[params.comments]
#enabled = true # default
#engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
#[params.comments.utterances]
#repo = "<github_username>/<github_reponame>"
#label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
#theme = "github-light"
#[params.comments.cactuscomments]
#siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
#serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
#serverName = "" # Defaults to cactus.chat

# the value of name should be an valid font awesome icon name (brands type)
# https://fontawesome.com/icons?d=gallery&s=brands
[[params.social]]
name = "github"
link = "https://github.com/pa-perz"
[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/in/pa-perz"
[[params.social]]
name = "twitter"
link = "https://twitter.com/pa_perz"
[[params.social]]
name = "email"
link = "pa_perz@outlook.es"  # no need for "mailto:" in the head